  
name: Dynnamic code Analysis - Valgrind
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install valgrind
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: make test
      run: make -C 3_Implementation/ test
    - name: Valgrind
      run: valgrind ./3_Implementation/Build/Test_Calculator.out
    - name: make distcheck
      run: make distcheck
